apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o52vwn571-go 
  janus-idp.io/tekton: o52vwn571-go
  backstage.io/kubernetes-id: o52vwn571-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o52vwn571-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml